export const galleries = {
  gallery1: [
    'public/foods/anh-nguyen-kcA-c3f_3FE-unsplash.jpg',
    'public/foods/casey-lee-awj7sRviVXo-unsplash.jpg',
    'public/foods/chad-montano-eeqbbemH9-c-unsplash.jpg',
    'public/foods/chad-montano-MqT0asuoIcU-unsplash.jpg',
    'public/foods/eiliv-aceron-ZuIDLSz3XLg-unsplash.jpg',
    'public/foods/joseph-gonzalez-fdlZBWIP0aM-unsplash.jpg',
    'public/foods/joseph-gonzalez-zcUgjyqEwe8-unsplash.jpg',
    'public/foods/rachel-park-hrlvr2ZlUNk-unsplash.jpg',
  ],
  gallery2: [
    'public/bikes/ashu-dadwal-Pt71Df4wxgs-unsplash.jpg',
    'public/bikes/bike1.jpg',
    'public/bikes/harley-davidson-eeTJKC_wz34-unsplash.jpg',
    'public/bikes/kushal-medhi-gw4enPeVQDM-unsplash.jpg',
    'public/bikes/rikas-rasheed-iq5jLDMVXZQ-unsplash.jpg',
    'public/bikes/sanjeev-nagaraj-caz59CGkQz8-unsplash.jpg',
    'public/bikes/sanjeev-nagaraj-E06AY-OUD7g-unsplash.jpg',
  ],
  gallery3: [
    'public/cycles/christin-hume-OYAj7gJbhlo-unsplash.jpg',
    'public/cycles/howard-bouchevereau-BRDO4C-0h_s-unsplash.jpg',
    'public/cycles/john-nzoka-n0iClJpvmPQ-unsplash.jpg',
    'public/cycles/kaur-kristjan-miUC0b1IVYU-unsplash.jpg',
    'public/cycles/santiago-pazos-bordon-Jj9dycup6HM-unsplash.jpg',
    'public/cycles/saurav-kundu-H8QttyFgroY-unsplash.jpg',
    'public/cycles/ting-tse-wang-0pqoAu5mW0s-unsplash.jpg',
  ],
};

export const sliderConfigs = {
  gallery1: {
    type: 'carousel',
    themes: {
      forest: {
        '--bg': 'linear-gradient(135deg, #4B352A 60%, #B2CD9C 100%)',
        '--primary': '#4B352A',
        '--secondary': '#B2CD9C',
        '--text': '#210F37',
        '--btn-bg': '#CA7842',
        '--btn-color': '#F0F2BD',
        '--btn-hover-bg': '#F0F2BD',
        '--btn-hover-color': '#4B352A',
        '--border': '4px solid #CA7842',
        '--dot-bg': '#B2CD9C',
        '--dot-active-bg': '#CA7842',
      },
      pastel: {
        '--bg': 'linear-gradient(135deg, #CADCAE 60%, #EDA35A 100%)',
        '--primary': '#EDA35A',
        '--secondary': '#FEE8D9',
        '--text': '#4F1C51',
        '--btn-bg': '#E1E9C9',
        '--btn-color': '#210F37',
        '--btn-hover-bg': '#EDA35A',
        '--btn-hover-color': '#FEE8D9',
        '--border': '4px solid #EDA35A',
        '--dot-bg': '#EDA35A',
        '--dot-active-bg': '#FEE8D9',
      },
      retro: {
        '--bg': 'linear-gradient(135deg, #210F37 60%, #DCA06D 100%)',
        '--primary': '#A55B4B',
        '--secondary': '#DCA06D',
        '--text': '#F0F2BD',
        '--btn-bg': '#4F1C51',
        '--btn-color': '#FEE8D9',
        '--btn-hover-bg': '#A55B4B',
        '--btn-hover-color': '#210F37',
        '--border': '4px double #A55B4B',
        '--dot-bg': '#DCA06D',
        '--dot-active-bg': '#A55B4B',
      },
      default: {},
    },
  },
  gallery2: {
    type: 'carousel',
    themes: {
      vibrant: {
        '--bg': 'linear-gradient(135deg, #450693 60%, #FFC400 100%)',
        '--primary': '#8C00FF',
        '--secondary': '#FF3F7F',
        '--text': '#37353E',
        '--btn-bg': '#FFC400',
        '--btn-color': '#fff',
        '--btn-hover-bg': '#FF3F7F',
        '--btn-hover-color': '#450693',
        '--border': '4px solid #8C00FF',
        '--dot-bg': '#FFC400',
        '--dot-active-bg': '#FF3F7F',
      },
      sand: {
        '--bg': 'linear-gradient(135deg, #B6AE9F 60%, #FBF3D1 100%)',
        '--primary': '#C5C7BC',
        '--secondary': '#DEDED1',
        '--text': '#44444E',
        '--btn-bg': '#FBF3D1',
        '--btn-color': '#37353E',
        '--btn-hover-bg': '#DEDED1',
        '--btn-hover-color': '#B6AE9F',
        '--border': '4px solid #C5C7BC',
        '--dot-bg': '#DEDED1',
        '--dot-active-bg': '#B6AE9F',
      },
      dusk: {
        '--bg': 'linear-gradient(135deg, #37353E 60%, #D3DAD9 100%)',
        '--primary': '#44444E',
        '--secondary': '#715A5A',
        '--text': '#FBF3D1',
        '--btn-bg': '#715A5A',
        '--btn-color': '#D3DAD9',
        '--btn-hover-bg': '#44444E',
        '--btn-hover-color': '#FFC400',
        '--border': '4px double #44444E',
        '--dot-bg': '#715A5A',
        '--dot-active-bg': '#D3DAD9',
      },
      default: {},
    },
  },
  gallery3: {
    type: 'carousel',
    themes: {
      aqua: {
        '--bg': 'linear-gradient(120deg, #66D2CE 60%, #E3D2C3 100%)',
        '--primary': '#2DAA9E',
        '--secondary': '#EAEAEA',
        '--text': '#8D0B41',
        '--btn-bg': '#2DAA9E',
        '--btn-color': '#EAEAEA',
        '--btn-hover-bg': '#E3D2C3',
        '--btn-hover-color': '#66D2CE',
        '--border': '5px solid #2DAA9E',
        '--dot-bg': '#EAEAEA',
        '--dot-active-bg': '#2DAA9E',
      },
      ocean: {
        '--bg': 'linear-gradient(120deg, #F2EFE7 60%, #2973B2 100%)',
        '--primary': '#9ACBD0',
        '--secondary': '#48A6A7',
        '--text': '#D39D55',
        '--btn-bg': '#2973B2',
        '--btn-color': '#FFF8E6',
        '--btn-hover-bg': '#9ACBD0',
        '--btn-hover-color': '#2973B2',
        '--border': '5px solid #2973B2',
        '--dot-bg': '#9ACBD0',
        '--dot-active-bg': '#2973B2',
      },
      rose: {
        '--bg': 'linear-gradient(120deg, #8D0B41 60%, #FFF8E6 100%)',
        '--primary': '#D39D55',
        '--secondary': '#D6CFB4',
        '--text': '#2DAA9E',
        '--btn-bg': '#8D0B41',
        '--btn-color': '#FFF8E6',
        '--btn-hover-bg': '#D39D55',
        '--btn-hover-color': '#8D0B41',
        '--border': '5px double #8D0B41',
        '--dot-bg': '#D6CFB4',
        '--dot-active-bg': '#8D0B41',
      },
      default: {},
    },
  },
};
