export const galleries = {
  gallery1: [
    'public/foods/anh-nguyen-kcA-c3f_3FE-unsplash.jpg',
    'public/foods/casey-lee-awj7sRviVXo-unsplash.jpg',
    'public/foods/chad-montano-eeqbbemH9-c-unsplash.jpg',
    'public/foods/chad-montano-MqT0asuoIcU-unsplash.jpg',
    'public/foods/eiliv-aceron-ZuIDLSz3XLg-unsplash.jpg',
    'public/foods/joseph-gonzalez-fdlZBWIP0aM-unsplash.jpg',
    'public/foods/joseph-gonzalez-zcUgjyqEwe8-unsplash.jpg',
    'public/foods/rachel-park-hrlvr2ZlUNk-unsplash.jpg',
  ],
  gallery2: [
    'public/bikes/ashu-dadwal-Pt71Df4wxgs-unsplash.jpg',
    'public/bikes/bike1.jpg',
    'public/bikes/harley-davidson-eeTJKC_wz34-unsplash.jpg',
    'public/bikes/kushal-medhi-gw4enPeVQDM-unsplash.jpg',
    'public/bikes/rikas-rasheed-iq5jLDMVXZQ-unsplash.jpg',
    'public/bikes/sanjeev-nagaraj-caz59CGkQz8-unsplash.jpg',
    'public/bikes/sanjeev-nagaraj-E06AY-OUD7g-unsplash.jpg',
  ],
  gallery3: [
    'public/cycles/christin-hume-OYAj7gJbhlo-unsplash.jpg',
    'public/cycles/howard-bouchevereau-BRDO4C-0h_s-unsplash.jpg',
    'public/cycles/john-nzoka-n0iClJpvmPQ-unsplash.jpg',
    'public/cycles/kaur-kristjan-miUC0b1IVYU-unsplash.jpg',
    'public/cycles/santiago-pazos-bordon-Jj9dycup6HM-unsplash.jpg',
    'public/cycles/saurav-kundu-H8QttyFgroY-unsplash.jpg',
    'public/cycles/ting-tse-wang-0pqoAu5mW0s-unsplash.jpg',
  ],
};
